apiVersion: apps/v1
kind: Deployment
metadata:
  name: whiskc-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whiskc-auth
  template:
    metadata:
      labels:
        app: whiskc-auth
    spec:
      containers:
        - name: whiskc-auth
          image: registry.digitalocean.com/whiskc/whiskc/auth
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: whiskc-auth
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: api
  selector:
    app: whiskc-auth
  type: ClusterIP
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-nginx
spec:
  acme:
    email: cuong95nd@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-nginx-private-key
    solvers:
      - http01:
          ingress:
            class: nginx
